### PR TITLE
Improving the instructions

### PR DESCRIPTION
**Pull request by andrelcalado**
The first point is about git:
When i'm tried to install the repository in my project, i had a problem about cloned a repository into to another repository, so when i tried to do a push to project repository, the git had some errors. So i'm deleted the repository in the project, downloaded again and put to project folder, but not using the git clone and the problem is solved

The second point is about when the folder is the current name of this project (vtex-react-checkout): In the first moment, i had not a folder 'checkout-ui-custom', so i put the repository folder into my project and try to run, but any changes don't resulted in workspace, so when i changed the folder name to 'checkout- ui-custom', its works.

So i changed some words and put more, to explain better this points.

### CODE REVIEW

**Comment by gustavokei** [comment]
Hi, thanks for contributing for this project! I really appreciate your feedback!!

I have some points I would like to discuss before merging your changes:

- We can change the word "clone" to "download", however there is no need for the word "to" in

`Download this repository into your checkout-ui-custom folder "to" and run yarn`

The sentence would be gramatically incorrect.

- Considering the issue is regarding folder structure, wouldn't it be better if we used a graphical example just like we have in the [folder structure section](https://github.com/gustavokei/vtex-react-checkout#folder-structure)? Maybe mentioning the root structure beforehand could reduce uncertainties in the installation process.

- Also, I think we are missing a step before the current initial instructions which is properly installing `checkout-ui-custom` by adding the builder `"checkout-ui-custom": "0.x"` into the `manifest.json` file and/or running `vtex install vtex.checkout-ui-custom`. Not sure which is it, we should clarify this.

What are your thoughts?

**Comment by andrelcalado** [comment]
Hi, Kei!

It's an honor to may contribute to this project.
I did some changes in commit about your comments above, so...

The first change is about grammatical sentence, no problem, i did it.

The second change is about of mentioning folder structure section. I included a mention to the folder structure section and change the root name in folder structure section to `checkout-ui-custom`.

To end, i included a new section (Requirements), to talk about the project requirements to run without problems.

What you think?

**Comment by gustavokei** [comment]
Hey, thanks for the update! I can clearly see some improvements.

I have installed this project into a vtex store once again in order to properly understand the installation process. Here's what I found out:
- Considering this could be a separated app, we only need `yarn` installed, a folder named `checkout-ui-custom` with `checkout6-custom.css` + `checkout6-custom.js`, and a `manifest.json` with the contents:
```json
{
  "vendor": "your-vendor", // your vendor name
  "name": "vtex-react-checkout", // your app name
  "version": "1.0.0", // your version
  "private": true,
  "builders": {
    "checkout-ui-custom": "0.x"
  },
  "$schema": "https://raw.githubusercontent.com/vtex/node-vtex-api/master/gen/manifest.schema"
}
```
Just like the image bellow.
Screenshot 2023-04-04 at 11 36 13

Then, login into your vtex account, creating a workspace with `vtex use myws`, and running `vtex link` will install this project at `https://myws--myaccount.myvtex.com/checkout`. 
Also, I believe there is no need to run `vtex install vtex.checkout-ui-custom` nor following the steps from [checkout-ui-custom](https://github.com/vtex-apps/checkout-ui-custom#configuration), can you confirm that? If so, we should update the current instructions.

- The `PS` section might be a bit confusing. Wouldn't it be better if we instruct developers - on the first step - to create a `checkout-ui-custom` folder at the root of their app and then downloading this project inside of it?

**Comment by gustavokei** [comment]
Hi, seems like [these instructions](https://github.com/gustavokei/vtex-react-checkout/issues/3#issuecomment-1557246253) worked for some users, perhaps we can formalize it into the documentation. What are your thoughts?

**Comment by gustavokei** [comment]
Hello, I have updated the README with the instructions of that issue. It seems that they have worked for more users. Therefore, I am closing this PR.

**Pull request closed without merging**
